export const EVENT = {
  REQUEST_PUZZLE_HINT_ERROR: 'REQUEST_PUZZLE_HINT_ERROR',
  AUTHENTICATE_DEVICE_UNKNOWN_ERROR: 'AUTHENTICATE_DEVICE_UNKNOWN_ERROR',
  DELETE_PROGRESS_ERROR: 'DELETE_PROGRESS_ERROR',
  ERROR_VIEW_ERROR: 'ERROR_VIEW_ERROR',
} as const;
export type EVENT = (typeof EVENT)[keyof typeof EVENT];
