name: Mobile

on:
  push:
    branches: [main]
    paths:
      - "mobile/**"
      - "shared/**"
  pull_request:
    branches: [main]
    paths:
      - "mobile/**"
      - "shared/**"

jobs:
  lint_typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile --filter game-brain-mobile...

      - name: Generate GraphQL types
        run: pnpm --filter game-brain-mobile generate

      - name: Lint
        run: pnpm --filter game-brain-mobile lint

      - name: Typecheck
        run: pnpm --filter game-brain-mobile tsc

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile --filter game-brain-mobile...

      - name: Generate GraphQL types
        run: pnpm --filter game-brain-mobile generate

      - name: Test
        run: pnpm --filter game-brain-mobile test:ci
